DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
username VARCHAR(50) PRIMARY KEY,
password CHAR(60) NOT NULL
);

DROP TABLE IF EXISTS tickers CASCADE;
CREATE TABLE tickers(
ticker VARCHAR(10) PRIMARY KEY
);

DROP TABLE IF EXISTS users_to_ticker CASCADE;
CREATE TABLE users_to_ticker(
username VARCHAR(50) NOT NULL,
ticker VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS user_follows CASCADE;
CREATE TABLE user_follows(
followed_username VARCHAR(50) NOT NULL,
follower_username VARCHAR(50) NOT NULL
);
